// Curated catalog of well-known phages to seed the database
export interface PhageCatalogEntry {
  slug: string;
  name: string;
  accession: string; // RefSeq or GenBank accession
  family: string;
  genus: string;
  host: string;
  morphology: string;
  lifecycle: string;
  genomeType: string;
  baltimoreGroup: string;
  description: string;
  pdbIds?: string[]; // PDB IDs for 3D models
}

export const PHAGE_CATALOG: PhageCatalogEntry[] = [
  {
    slug: 'lambda',
    name: 'Enterobacteria phage lambda',
    accession: 'NC_001416.1',
    family: 'Siphoviridae',
    genus: 'Lambdavirus',
    host: 'Escherichia coli K-12',
    morphology: 'siphovirus',
    lifecycle: 'lysogenic',
    genomeType: 'dsDNA',
    baltimoreGroup: 'I',
    description: 'Lambda phage is a temperate bacteriophage that infects E. coli. It has an icosahedral capsid and a long, flexible tail. Famous for its role in molecular biology research.',
    pdbIds: ['7VI9'],  // 8K35 no longer available on RCSB
  },
  {
    slug: 't4',
    name: 'Enterobacteria phage T4',
    accession: 'NC_000866.4',
    family: 'Myoviridae',
    genus: 'Tequatrovirus',
    host: 'Escherichia coli B',
    morphology: 'myovirus',
    lifecycle: 'lytic',
    genomeType: 'dsDNA',
    baltimoreGroup: 'I',
    description: 'T4 is a large, lytic bacteriophage with a complex contractile tail. It is one of the most well-studied viruses and has been instrumental in understanding DNA replication and recombination.',
    pdbIds: ['5VF3'],
  },
  {
    slug: 't7',
    name: 'Enterobacteria phage T7',
    accession: 'NC_001604.1',
    family: 'Podoviridae',
    genus: 'Teseptimavirus',
    host: 'Escherichia coli',
    morphology: 'podovirus',
    lifecycle: 'lytic',
    genomeType: 'dsDNA',
    baltimoreGroup: 'I',
    description: 'T7 is a lytic bacteriophage with a short tail. Its RNA polymerase is widely used in molecular biology for in vitro transcription.',
    pdbIds: ['3J4G'],
  },
  {
    slug: 'phix174',
    name: 'Escherichia phage phiX174',
    accession: 'NC_001422.1',
    family: 'Microviridae',
    genus: 'Sinsheimervirus',
    host: 'Escherichia coli C',
    morphology: 'microvirus',
    lifecycle: 'lytic',
    genomeType: 'ssDNA',
    baltimoreGroup: 'II',
    description: 'PhiX174 was the first DNA-based genome to be fully sequenced (1977). It has a small, circular, single-stranded DNA genome with overlapping genes.',
    pdbIds: ['2BPA'],
  },
  {
    slug: 'ms2',
    name: 'Enterobacteria phage MS2',
    accession: 'NC_001417.2',
    family: 'Fiersviridae',
    genus: 'Emesvirus',
    host: 'Escherichia coli',
    morphology: 'levivirus',
    lifecycle: 'lytic',
    genomeType: 'ssRNA',
    baltimoreGroup: 'IV',
    description: 'MS2 is a small RNA phage that was the first genome of any kind to be fully sequenced (1976). Used extensively in virology and molecular biology research.',
    pdbIds: ['2MS2'],
  },
  {
    slug: 'm13',
    name: 'Escherichia phage M13',
    accession: 'NC_003287.2',
    family: 'Inoviridae',
    genus: 'Inovirus',
    host: 'Escherichia coli',
    morphology: 'filamentous',
    lifecycle: 'chronic',
    genomeType: 'ssDNA',
    baltimoreGroup: 'II',
    description: 'M13 is a filamentous phage that infects F-pilus bearing E. coli. Widely used in phage display technology and DNA sequencing.',
    pdbIds: ['2MJZ'],
  },
  {
    slug: 'p22',
    name: 'Salmonella phage P22',
    accession: 'NC_002371.2',
    family: 'Podoviridae',
    genus: 'Lederbergvirus',
    host: 'Salmonella enterica',
    morphology: 'podovirus',
    lifecycle: 'lysogenic',
    genomeType: 'dsDNA',
    baltimoreGroup: 'I',
    description: 'P22 is a temperate phage that infects Salmonella. Important for studies of transduction and phage assembly.',
    pdbIds: ['5UU5'],
  },
  {
    slug: 'phi29',
    name: 'Bacillus phage phi29',
    accession: 'NC_011048.1',
    family: 'Podoviridae',
    genus: 'Salasvirus',
    host: 'Bacillus subtilis',
    morphology: 'podovirus',
    lifecycle: 'lytic',
    genomeType: 'dsDNA',
    baltimoreGroup: 'I',
    description: 'Phi29 is notable for its DNA polymerase which has exceptional strand displacement activity, used in whole genome amplification.',
    pdbIds: ['1MN8'],
  },
  {
    slug: 'mu',
    name: 'Escherichia phage Mu',
    accession: 'NC_000929.1',
    family: 'Myoviridae',
    genus: 'Muvirus',
    host: 'Escherichia coli K-12',
    morphology: 'myovirus',
    lifecycle: 'lysogenic',
    genomeType: 'dsDNA',
    baltimoreGroup: 'I',
    description: 'Mu (mutator) phage is a transposable phage that replicates by transposition, causing mutations when it inserts into the host genome.',
    pdbIds: ['4FCY', '1WRU', '5YVQ'],
  },
  {
    slug: 'phi6',
    name: 'Pseudomonas phage phi6',
    accession: 'NC_003714.1',
    family: 'Cystoviridae',
    genus: 'Cystovirus',
    host: 'Pseudomonas syringae',
    morphology: 'cystovirus',
    lifecycle: 'lytic',
    genomeType: 'dsRNA',
    baltimoreGroup: 'III',
    description: 'Phi6 is one of the few known dsRNA phages. It has a segmented genome and an enveloped virion, making it structurally unique among phages.',
    pdbIds: ['4BTG'],
  },
  {
    slug: 'spbeta',
    name: 'Bacillus phage SPbeta',
    accession: 'NC_001884.1',
    family: 'Siphoviridae',
    genus: 'Spbetavirus',
    host: 'Bacillus subtilis',
    morphology: 'siphovirus',
    lifecycle: 'lysogenic',
    genomeType: 'dsDNA',
    baltimoreGroup: 'I',
    description: 'SPbeta is a temperate phage that infects B. subtilis. It has been important for understanding Gram-positive phage biology.',
    pdbIds: ['5Y24', '6HP7', '5XYB'],
  },
  {
    slug: 't5',
    name: 'Enterobacteria phage T5',
    accession: 'NC_005859.1',
    family: 'Siphoviridae',
    genus: 'Tequintavirus',
    host: 'Escherichia coli',
    morphology: 'siphovirus',
    lifecycle: 'lytic',
    genomeType: 'dsDNA',
    baltimoreGroup: 'I',
    description: 'T5 is a lytic phage with a unique two-step DNA injection mechanism. First, only 8% of the genome enters, then the rest follows.',
    pdbIds: ['8ZVI', '6OMC', '5TJT'],
  },
];

// Get phage catalog entry by slug
export function getPhageEntry(slug: string): PhageCatalogEntry | undefined {
  return PHAGE_CATALOG.find(p => p.slug === slug);
}
