// Curated catalog of well-known phages to seed the database
export interface PhageCatalogEntry {
  slug: string;
  name: string;
  accession: string; // RefSeq or GenBank accession
  family: string;
  genus: string;
  host: string;
  morphology: string;
  lifecycle: string;
  genomeType: string;
  baltimoreGroup: string;
  description: string;
  pdbIds?: string[]; // PDB IDs for 3D models
}

export const PHAGE_CATALOG: PhageCatalogEntry[] = [
  {
    slug: 'lambda',
    name: 'Enterobacteria phage lambda',
    accession: 'NC_001416.1',
    family: 'Siphoviridae',
    genus: 'Lambdavirus',
    host: 'Escherichia coli K-12',
    morphology: 'siphovirus',
    lifecycle: 'lysogenic',
    genomeType: 'dsDNA',
    baltimoreGroup: 'I',
    description: 'Lambda phage is a temperate bacteriophage that infects E. coli. It has an icosahedral capsid and a long, flexible tail. Famous for its role in molecular biology research.',
    pdbIds: ['7VI9'],  // 8K35 no longer available on RCSB
  },
  {
    slug: 't4',
    name: 'Enterobacteria phage T4',
    accession: 'NC_000866.4',
    family: 'Myoviridae',
    genus: 'Tequatrovirus',
    host: 'Escherichia coli B',
    morphology: 'myovirus',
    lifecycle: 'lytic',
    genomeType: 'dsDNA',
    baltimoreGroup: 'I',
    description: 'T4 is a large, lytic bacteriophage with a complex contractile tail. It is one of the most well-studied viruses and has been instrumental in understanding DNA replication and recombination.',
    pdbIds: ['5VF3'],
  },
  {
    slug: 't7',
    name: 'Enterobacteria phage T7',
    accession: 'NC_001604.1',
    family: 'Podoviridae',
    genus: 'Teseptimavirus',
    host: 'Escherichia coli',
    morphology: 'podovirus',
    lifecycle: 'lytic',
    genomeType: 'dsDNA',
    baltimoreGroup: 'I',
    description: 'T7 is a lytic bacteriophage with a short tail. Its RNA polymerase is widely used in molecular biology for in vitro transcription.',
    pdbIds: ['3J4G'],
  },
  {
    slug: 'phix174',
    name: 'Escherichia phage phiX174',
    accession: 'NC_001422.1',
    family: 'Microviridae',
    genus: 'Sinsheimervirus',
    host: 'Escherichia coli C',
    morphology: 'microvirus',
    lifecycle: 'lytic',
    genomeType: 'ssDNA',
    baltimoreGroup: 'II',
    description: 'PhiX174 was the first DNA-based genome to be fully sequenced (1977). It has a small, circular, single-stranded DNA genome with overlapping genes.',
    pdbIds: ['2BPA'],
  },
  {
    slug: 'ms2',
    name: 'Enterobacteria phage MS2',
    accession: 'NC_001417.2',
    family: 'Fiersviridae',
    genus: 'Emesvirus',
    host: 'Escherichia coli',
    morphology: 'levivirus',
    lifecycle: 'lytic',
    genomeType: 'ssRNA',
    baltimoreGroup: 'IV',
    description: 'MS2 is a small RNA phage that was the first genome of any kind to be fully sequenced (1976). Used extensively in virology and molecular biology research.',
    pdbIds: ['2MS2'],
  },
  {
    slug: 'm13',
    name: 'Escherichia phage M13',
    accession: 'NC_003287.2',
    family: 'Inoviridae',
    genus: 'Inovirus',
    host: 'Escherichia coli',
    morphology: 'filamentous',
    lifecycle: 'chronic',
    genomeType: 'ssDNA',
    baltimoreGroup: 'II',
    description: 'M13 is a filamentous phage that infects F-pilus bearing E. coli. Widely used in phage display technology and DNA sequencing.',
    pdbIds: ['2MJZ'],
  },
  {
    slug: 'p22',
    name: 'Salmonella phage P22',
    accession: 'NC_002371.2',
    family: 'Podoviridae',
    genus: 'Lederbergvirus',
    host: 'Salmonella enterica',
    morphology: 'podovirus',
    lifecycle: 'lysogenic',
    genomeType: 'dsDNA',
    baltimoreGroup: 'I',
    description: 'P22 is a temperate phage that infects Salmonella. Important for studies of transduction and phage assembly.',
    pdbIds: ['5UU5'],
  },
  {
    slug: 'phi29',
    name: 'Bacillus phage phi29',
    accession: 'NC_011048.1',
    family: 'Podoviridae',
    genus: 'Salasvirus',
    host: 'Bacillus subtilis',
    morphology: 'podovirus',
    lifecycle: 'lytic',
    genomeType: 'dsDNA',
    baltimoreGroup: 'I',
    description: 'Phi29 is notable for its DNA polymerase which has exceptional strand displacement activity, used in whole genome amplification.',
    pdbIds: ['1MN8'],
  },
  {
    slug: 'mu',
    name: 'Escherichia phage Mu',
    accession: 'NC_000929.1',
    family: 'Myoviridae',
    genus: 'Muvirus',
    host: 'Escherichia coli K-12',
    morphology: 'myovirus',
    lifecycle: 'lysogenic',
    genomeType: 'dsDNA',
    baltimoreGroup: 'I',
    description: 'Mu (mutator) phage is a transposable phage that replicates by transposition, causing mutations when it inserts into the host genome.',
    pdbIds: ['4FCY', '1WRU', '5YVQ'],
  },
  {
    slug: 'phi6',
    name: 'Pseudomonas phage phi6',
    accession: 'NC_003714.1',
    family: 'Cystoviridae',
    genus: 'Cystovirus',
    host: 'Pseudomonas syringae',
    morphology: 'cystovirus',
    lifecycle: 'lytic',
    genomeType: 'dsRNA',
    baltimoreGroup: 'III',
    description: 'Phi6 is one of the few known dsRNA phages. It has a segmented genome and an enveloped virion, making it structurally unique among phages.',
    pdbIds: ['4BTG'],
  },
  {
    slug: 'spbeta',
    name: 'Bacillus phage SPbeta',
    accession: 'NC_001884.1',
    family: 'Siphoviridae',
    genus: 'Spbetavirus',
    host: 'Bacillus subtilis',
    morphology: 'siphovirus',
    lifecycle: 'lysogenic',
    genomeType: 'dsDNA',
    baltimoreGroup: 'I',
    description: 'SPbeta is a temperate phage that infects B. subtilis. It has been important for understanding Gram-positive phage biology.',
    pdbIds: ['5Y24', '6HP7', '5XYB'],
  },
  {
    slug: 't5',
    name: 'Enterobacteria phage T5',
    accession: 'NC_005859.1',
    family: 'Siphoviridae',
    genus: 'Tequintavirus',
    host: 'Escherichia coli',
    morphology: 'siphovirus',
    lifecycle: 'lytic',
    genomeType: 'dsDNA',
    baltimoreGroup: 'I',
    description: 'T5 is a lytic phage with a unique two-step DNA injection mechanism. First, only 8% of the genome enters, then the rest follows.',
    pdbIds: ['8ZVI', '6OMC', '5TJT'],
  },
  // === NEW PHAGES (12 additions for diversity) ===
  {
    slug: 'p1',
    name: 'Enterobacteria phage P1',
    accession: 'NC_005856.1',
    family: 'Myoviridae',
    genus: 'Peduovirus',
    host: 'Escherichia coli',
    morphology: 'myovirus',
    lifecycle: 'lysogenic',
    genomeType: 'dsDNA',
    baltimoreGroup: 'I',
    description: 'P1 is a temperate phage that uniquely maintains its prophage as a low-copy circular plasmid rather than integrating into the chromosome. Classic workhorse for generalized transduction and the Cre-lox recombination system.',
  },
  {
    slug: 'p2',
    name: 'Enterobacteria phage P2',
    accession: 'NC_001895.1',
    family: 'Myoviridae',
    genus: 'Peduovirus',
    host: 'Escherichia coli',
    morphology: 'myovirus',
    lifecycle: 'lysogenic',
    genomeType: 'dsDNA',
    baltimoreGroup: 'I',
    description: 'P2 is the founding member of the P2-like temperate phages (Peduovirinae). It has a contractile tail and integrates site-specifically into the host chromosome. Historically important in phage genetics research.',
  },
  {
    slug: 'n4',
    name: 'Enterobacteria phage N4',
    accession: 'NC_008720.1',
    family: 'Schitoviridae',
    genus: 'Enquatrovirus',
    host: 'Escherichia coli',
    morphology: 'podovirus',
    lifecycle: 'lytic',
    genomeType: 'dsDNA',
    baltimoreGroup: 'I',
    description: 'N4 is famous for its unusual transcription system: it injects its own RNA polymerase (vRNAP) along with its DNA. This virion-encapsidated RNAP transcribes early genes from hairpin promoters—a mechanism unlike T7 or T4.',
    pdbIds: ['2PO4', '3C2P'],
  },
  {
    slug: 'felixo1',
    name: 'Salmonella phage Felix O1',
    accession: 'NC_005282.1',
    family: 'Myoviridae',
    genus: 'Felixounavirus',
    host: 'Salmonella enterica',
    morphology: 'myovirus',
    lifecycle: 'lytic',
    genomeType: 'dsDNA',
    baltimoreGroup: 'I',
    description: 'Felix O1 is the classic Salmonella-typing phage, historically used to identify Salmonella species. It has an exceptionally broad host range within Salmonella and is a model for applied phage microbiology.',
  },
  {
    slug: 'd29',
    name: 'Mycobacterium phage D29',
    accession: 'NC_001900.1',
    family: 'Siphoviridae',
    genus: 'Cheoctovirus',
    host: 'Mycobacterium smegmatis',
    morphology: 'siphovirus',
    lifecycle: 'lytic',
    genomeType: 'dsDNA',
    baltimoreGroup: 'I',
    description: 'D29 is an iconic lytic mycobacteriophage used extensively in teaching (SEA-PHAGES program) and tuberculosis research. It infects both fast-growing (M. smegmatis) and slow-growing (M. tuberculosis) mycobacteria.',
    pdbIds: ['3HC7'],
  },
  {
    slug: 'l5',
    name: 'Mycobacterium phage L5',
    accession: 'NC_001335.1',
    family: 'Siphoviridae',
    genus: 'Laphivirus',
    host: 'Mycobacterium smegmatis',
    morphology: 'siphovirus',
    lifecycle: 'lysogenic',
    genomeType: 'dsDNA',
    baltimoreGroup: 'I',
    description: 'L5 is a temperate mycobacteriophage and the first mycobacteriophage genome sequenced. Its integrase system is used for site-specific integration into mycobacterial chromosomes. Close relative of D29 (which lost lysogeny genes).',
    pdbIds: ['8EDU'], // Mycobacteriophage Muddy capsid - same HK97-fold Cluster A architecture as L5
  },
  {
    slug: 'phic31',
    name: 'Streptomyces phage phiC31',
    accession: 'NC_001978.1',
    family: 'Siphoviridae',
    genus: 'Phic31virus',
    host: 'Streptomyces coelicolor',
    morphology: 'siphovirus',
    lifecycle: 'lysogenic',
    genomeType: 'dsDNA',
    baltimoreGroup: 'I',
    description: 'PhiC31 is famous for its serine integrase, a powerful tool for site-specific genome integration in eukaryotes. The integrase mediates unidirectional recombination between attB and attP sites, widely used in gene therapy and transgenics.',
    pdbIds: ['4BQQ'],
  },
  {
    slug: 'phikz',
    name: 'Pseudomonas phage phiKZ',
    accession: 'NC_004629.1',
    family: 'Chimalliviridae',
    genus: 'Phikzvirus',
    host: 'Pseudomonas aeruginosa',
    morphology: 'myovirus',
    lifecycle: 'lytic',
    genomeType: 'dsDNA',
    baltimoreGroup: 'I',
    description: 'PhiKZ is a "jumbo phage" with a massive 280 kb genome—larger than some bacteria. It forms a nucleus-like compartment during infection that protects its DNA from host defenses. Model for understanding giant phage biology.',
    pdbIds: ['3SPE', '3BKH'],
  },
  {
    slug: 'prd1',
    name: 'Enterobacteria phage PRD1',
    accession: 'NC_001421.2',
    family: 'Tectiviridae',
    genus: 'Alphatectivirus',
    host: 'Escherichia coli',
    morphology: 'tectivirus',
    lifecycle: 'lytic',
    genomeType: 'dsDNA',
    baltimoreGroup: 'I',
    description: 'PRD1 is a tailless phage with an internal lipid membrane beneath its icosahedral capsid. It infects bacteria carrying conjugative plasmids (IncP, N, W). Structurally related to adenovirus despite infecting bacteria—evidence of ancient viral lineages.',
    pdbIds: ['1W8X', '1HX6'],
  },
  {
    slug: 'pm2',
    name: 'Pseudoalteromonas phage PM2',
    accession: 'NC_000867.1',
    family: 'Corticoviridae',
    genus: 'Corticovirus',
    host: 'Pseudoalteromonas espejiana',
    morphology: 'corticovirus',
    lifecycle: 'lytic',
    genomeType: 'dsDNA',
    baltimoreGroup: 'I',
    description: 'PM2 is a marine phage and the first virus shown to contain lipids as structural components. Its circular genome is the most tightly supercoiled DNA known. Sole member of Corticoviridae—a unique structural lineage.',
    pdbIds: ['2W0C'],
  },
  {
    slug: 'qbeta',
    name: 'Enterobacteria phage Qbeta',
    accession: 'NC_001890.1',
    family: 'Fiersviridae',
    genus: 'Qubevirus',
    host: 'Escherichia coli',
    morphology: 'levivirus',
    lifecycle: 'lytic',
    genomeType: 'ssRNA',
    baltimoreGroup: 'IV',
    description: 'Qβ is an ssRNA phage related to MS2 but with distinct biology. Its RNA-dependent RNA polymerase (Qβ replicase) was key to understanding RNA replication and is used in isothermal amplification. The capsid is stabilized by disulfide bonds.',
    pdbIds: ['1QBE', '5VLZ'],
  },
  {
    slug: 't1',
    name: 'Enterobacteria phage T1',
    accession: 'NC_005833.1',
    family: 'Drexlerviridae',
    genus: 'Tunavirus',
    host: 'Escherichia coli',
    morphology: 'siphovirus',
    lifecycle: 'lytic',
    genomeType: 'dsDNA',
    baltimoreGroup: 'I',
    description: 'T1 is one of the original seven "T phages" but the least studied due to its notorious stability when dried—a lab contamination hazard. It has a long flexible tail and uses a headful packaging mechanism with generalized transduction capability.',
    pdbIds: ['9KZJ'], // Cryo-EM structure of bacteriophage T1 capsid (2024)
  },
];

// Get phage catalog entry by slug
export function getPhageEntry(slug: string): PhageCatalogEntry | undefined {
  return PHAGE_CATALOG.find(p => p.slug === slug);
}
